#pragma once
// ЗГЕНЕРОВАНО tools/gen_drone_configs.py з data/testing_data/*/NN_config.json - НЕ РЕДАГУВАТИ ВРУЧНУ.
// Конфіги дрона, вшиті в прошивку ESP32 готовими числами.
#include <array>

#include "types.hpp"

struct EmbeddedDroneConfig {
  const char* name;
  DroneConfig drone;
  float physicsTimeStep;
};

// Номер тесту N (1..10) - елемент з індексом N - 1
inline constexpr std::array<EmbeddedDroneConfig, 10> kEmbeddedDroneConfigs{{
  {.name = "01_sample_circles",
   .drone = {.startPos = {.x = 150.0f, .y = 150.0f},
             .altitude = 100.0f,
             .initialDir = 0.0f,
             .v0 = 10.0f,
             .accelerationPath = 10.0f,
             .simTimeStep = 0.1f,
             .hitRadius = 3.0f,
             .angularSpeed = 1.0f,
             .turnThreshold = 0.1f},
   .physicsTimeStep = 0.01f},
  {.name = "02_eliptic_trajectories",
   .drone = {.startPos = {.x = 200.0f, .y = 200.0f},
             .altitude = 100.0f,
             .initialDir = 0.5f,
             .v0 = 12.0f,
             .accelerationPath = 15.0f,
             .simTimeStep = 0.1f,
             .hitRadius = 3.0f,
             .angularSpeed = 1.0f,
             .turnThreshold = 0.1f},
   .physicsTimeStep = 0.01f},
  {.name = "03_visimky_lissaju_1-2",
   .drone = {.startPos = {.x = 100.0f, .y = 100.0f},
             .altitude = 80.0f,
             .initialDir = 0.0f,
             .v0 = 10.0f,
             .accelerationPath = 10.0f,
             .simTimeStep = 0.1f,
             .hitRadius = 3.0f,
             .angularSpeed = 1.0f,
             .turnThreshold = 0.1f},
   .physicsTimeStep = 0.01f},
  {.name = "04_star_trajectories",
   .drone = {.startPos = {.x = 123.0f, .y = 123.0f},
             .altitude = 120.0f,
             .initialDir = 1.0f,
             .v0 = 15.0f,
             .accelerationPath = 20.0f,
             .simTimeStep = 0.1f,
             .hitRadius = 3.0f,
             .angularSpeed = 0.8f,
             .turnThreshold = 0.1f},
   .physicsTimeStep = 0.01f},
  {.name = "05_lissaju_complex_curves",
   .drone = {.startPos = {.x = 50.0f, .y = 250.0f},
             .altitude = 100.0f,
             .initialDir = 0.0f,
             .v0 = 10.0f,
             .accelerationPath = 10.0f,
             .simTimeStep = 0.1f,
             .hitRadius = 3.0f,
             .angularSpeed = 1.0f,
             .turnThreshold = 0.1f},
   .physicsTimeStep = 0.01f},
  {.name = "06_fast_drone_slow_targets",
   .drone = {.startPos = {.x = 67.0f, .y = 67.0f},
             .altitude = 100.0f,
             .initialDir = 0.78f,
             .v0 = 20.0f,
             .accelerationPath = 30.0f,
             .simTimeStep = 0.1f,
             .hitRadius = 3.0f,
             .angularSpeed = 1.5f,
             .turnThreshold = 0.1f},
   .physicsTimeStep = 0.01f},
  {.name = "07_heavy_ammo",
   .drone = {.startPos = {.x = 100.0f, .y = 100.0f},
             .altitude = 80.0f,
             .initialDir = 0.7f,
             .v0 = 10.0f,
             .accelerationPath = 10.0f,
             .simTimeStep = 0.1f,
             .hitRadius = 4.0f,
             .angularSpeed = 1.0f,
             .turnThreshold = 0.1f},
   .physicsTimeStep = 0.01f},
  {.name = "08_gliding_ammo",
   .drone = {.startPos = {.x = 100.0f, .y = 300.0f},
             .altitude = 150.0f,
             .initialDir = 0.0f,
             .v0 = 12.0f,
             .accelerationPath = 12.0f,
             .simTimeStep = 0.1f,
             .hitRadius = 3.0f,
             .angularSpeed = 1.0f,
             .turnThreshold = 0.1f},
   .physicsTimeStep = 0.01f},
  {.name = "09_cardioids_eptirohoids",
   .drone = {.startPos = {.x = 250.0f, .y = 100.0f},
             .altitude = 100.0f,
             .initialDir = 1.57f,
             .v0 = 10.0f,
             .accelerationPath = 8.0f,
             .simTimeStep = 0.1f,
             .hitRadius = 3.0f,
             .angularSpeed = 2.0f,
             .turnThreshold = 0.1f},
   .physicsTimeStep = 0.01f},
  {.name = "10_extreme_far_fast",
   .drone = {.startPos = {.x = 0.0f, .y = 0.0f},
             .altitude = 100.0f,
             .initialDir = 0.785f,
             .v0 = 25.0f,
             .accelerationPath = 50.0f,
             .simTimeStep = 0.1f,
             .hitRadius = 2.0f,
             .angularSpeed = 0.5f,
             .turnThreshold = 0.1f},
   .physicsTimeStep = 0.01f},
}};
